#!/usr/bin/env python3
"""Write the option reference in docs/guide.html from 'hddscan --help'.

The reference on the site is generated, never typed, for the same reason the
man page is checked against usage(): a second copy of the options written by
hand drifts, and a reader has no way to know which one is wrong.  The section
between the OPTIONS markers is replaced wholesale; everything else in the page
is left alone.

    tools/options.py            # rewrite the section
    tools/options.py --check    # say nothing and exit 0 if it is current
"""
import html
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(ROOT, "docs", "guide.html")
BEGIN = "<!-- BEGIN OPTIONS: generated by tools/options.py from hddscan --help; do not edit -->"
END = "<!-- END OPTIONS -->"
DESC_COL = 25


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def parse(text):
    """[(heading, [(term, [desc lines])])], plus the lines before the first"""
    lines = text.split("\n")
    first = next(i for i, l in enumerate(lines) if l == "Selection")
    intro = lines[:first]
    groups, cur, entry = [], None, None
    for l in lines[first:]:
        if not l.strip():
            continue
        if not l.startswith(" "):
            if l.startswith("Exit status"):
                intro.append("")
                intro.append(l)
                continue
            cur = (l, [])
            groups.append(cur)
            entry = None
        elif l.startswith(" " * DESC_COL) and entry is not None:
            entry[1].append(l[DESC_COL:])
        else:
            body = l.lstrip()   # "      --no-tui" sits under "-i, --tui"
            m = re.match(r"(\S(?:.*?\S)?)(?: {2,}(.*))?$", body)
            term, desc = m.group(1), m.group(2)
            entry = (term, [desc] if desc else [])
            cur[1].append(entry)
    return intro, groups


def linkify(s, known):
    def sub(m):
        name = m.group(1)
        if name in known:
            return '<a href="#opt-%s"><code>%s</code></a>' % (name[2:], name)
        return "<code>%s</code>" % name
    return re.sub(r"(?<![\w/-])(--[a-z][a-z-]*[a-z])", sub, s)


def render(text):
    intro, groups = parse(text)
    known = set(re.findall(r"^ {2,8}(?:-\w, )?(--[a-z-]+)", text, re.M))
    out = [BEGIN]
    seen = set()
    usage = [l for l in intro if l.startswith(("Usage", "       "))]
    rest = [l for l in intro if l and l not in usage and not
            l.startswith("hddscan ")]
    out.append('<pre class="usage">%s</pre>' % html.escape("\n".join(usage)))
    out.append("<p>%s</p>" % linkify(html.escape(
        " ".join(l for l in rest if not l.startswith("Exit status"))), known))
    out.append('<nav class="optnav" aria-label="Option groups"><ul>')
    for head, _ in groups:
        out.append('<li><a href="#g-%s">%s</a></li>'
                   % (slug(head), html.escape(head.split(":")[0])))
    out.append("</ul></nav>")
    for head, entries in groups:
        out.append('<section class="optgroup" id="g-%s">' % slug(head))
        out.append("<h3>%s</h3>" % linkify(html.escape(head), known))
        out.append('<dl class="opts">')
        for term, desc in entries:
            m = re.match(r"(?:-\w, )?(--[a-z-]+)", term)
            # one anchor per option: --mode has an entry for each value
            anchor = ""
            if m and m.group(1) not in seen:
                seen.add(m.group(1))
                anchor = ' id="opt-%s"' % m.group(1)[2:]
            out.append("<dt%s><code>%s</code></dt>" % (anchor, html.escape(term)))
            if not desc:
                out.append("<dd></dd>")
            elif any(d.startswith("  ") for d in desc):
                # a table inside the text, such as the profiles: keep its shape
                out.append('<dd><pre class="optpre">%s</pre></dd>'
                           % linkify(html.escape("\n".join(desc)), known))
            else:
                out.append("<dd>%s</dd>" % linkify(html.escape(
                    " ".join(d.strip() for d in desc)), known))
        out.append("</dl></section>")
    exit_line = next((l for l in intro if l.startswith("Exit status")), "")
    if exit_line:
        out.append("<p class=\"exit\">%s</p>" % html.escape(exit_line))
    out.append(END)
    return "\n".join(out)


def main():
    hddscan = os.path.join(ROOT, "hddscan")
    text = subprocess.run([hddscan, "--help"], capture_output=True,
                          text=True, check=True).stdout
    page = open(PAGE).read()
    a, b = page.index(BEGIN), page.index(END) + len(END)
    new = page[:a] + render(text) + page[b:]
    if "--check" in sys.argv[1:]:
        if new != page:
            print("docs/guide.html is out of date with hddscan --help; "
                  "run tools/options.py")
            sys.exit(1)
        return
    if new != page:
        open(PAGE, "w").write(new)
        print("  rewrote the option reference in docs/guide.html")


if __name__ == "__main__":
    main()
